apiVersion: v1
kind: Service
metadata:
  name: {{ include "demoapp.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "demoapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "demoapp.selectorLabels" . | nindent 4 }}
